[test]
user="RGRIGGS0072"
password = "Tsalagi901!"
account = "OEZIERR-CNB82593"
warehouse = "compute_wh"
database = "datasets"
schema = "datasets"



[snowflake]
user="MORRIS_SRV"
password = "Tsalagi927!"
account = "OEZIERR-CNB82593"
warehouse = "MORRIS_WH"
database = "MORRIS_DIST"
schema = "MORRIS_SCH"